language: node_js
node_js:
  - "stable"
  - "9"
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run testonly:cov

notifications:
  email:
    on_success: never
